apiVersion: v1
kind: Service
metadata:
  name:      envoy
  namespace: envoy-lb
  labels:
    app:  envoy
spec:
  type: ClusterIP
  ports:
  - name: http-proxy
    port: 10001
    targetPort: 10001
    protocol: TCP
  selector:
    app: envoy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: envoy-lb
  labels:
    app: envoy
spec:
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy-debug-dev:latest
        imagePullPolicy: Always
        command:
        - /usr/local/bin/envoy
        args:
        - -c
        - /etc/envoy/config.yaml
        - -l
        - trace
        env:
        ports:
        - name: envoy-admin
          containerPort: 9902
        - name: envoy-data
          containerPort: 10001
        volumeMounts:
        - name: config-volume
          mountPath: /etc/envoy
      volumes:
        - name: config-volume
          configMap:
            name: envoy-configs
---
